### ISSUE TITLE
RTC INT pulling to ground but not triggering

### ISSUE THREAD

**Issue by StephenMoreOSU** [OPEnSLab-OSU/eDNA#1]
Tested using rtc trigger from Kawin, the code was functioning properly, however, RTC_Read was reading 1.44V from voltage divider across pullup and 30k resistor. The M0 was not reading the trigger.

FIX:
The solution to the bug was to take out the 30k between RTC_INT and RTC_Read and short the circuit, this allowed for the M0 to read trigger when RTC_INT was pulled down.

**Comment by kawinie** [comment]
Wrote RTC code for testing
